# Generated by Django 5.1.3 on 2024-11-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Название")),
                ("author", models.CharField(max_length=250, verbose_name="Автор")),
                ("description", models.TextField(verbose_name="Описание")),
                ("price", models.FloatField(default=500, verbose_name="Цена")),
                ("publication_date", models.DateField()),
            ],
        ),
    ]
