# Generated by Django 5.1.3 on 2025-02-05 13:48

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="main_photo",
            field=models.ImageField(
                blank=True,
                upload_to=catalog.models.get_upload_path,
                verbose_name="Главное фото",
            ),
        ),
    ]
